webtalk_init -webtalk_dir /home/extra/Xilinx/Vivado/2020.2/FRISC/FRISC.sim/zbrajalo_sim/behav/xsim/xsim.dir/Complete_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Jun 10 17:14:54 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "6e87c008-7a72-43f3-99e9-7550f276ae81" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "8bc2488f94e34900a59283ad6faa47b7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "289" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04.2 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1377.081 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "49" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "495 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "587 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "10411" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "11678" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "6.16_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "393716_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1769055410 -regid "" -xml /home/extra/Xilinx/Vivado/2020.2/FRISC/FRISC.sim/zbrajalo_sim/behav/xsim/xsim.dir/Complete_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/extra/Xilinx/Vivado/2020.2/FRISC/FRISC.sim/zbrajalo_sim/behav/xsim/xsim.dir/Complete_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/extra/Xilinx/Vivado/2020.2/FRISC/FRISC.sim/zbrajalo_sim/behav/xsim/xsim.dir/Complete_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
