#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Jan 22 07:15:04 CET 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim ALU_full_tb_behav -key {Behavioral:zbrajalo_sim:Functional:ALU_full_tb} -tclbatch ALU_full_tb.tcl -log simulate.log"
xsim ALU_full_tb_behav -key {Behavioral:zbrajalo_sim:Functional:ALU_full_tb} -tclbatch ALU_full_tb.tcl -log simulate.log

