#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Jun 10 19:29:00 CEST 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim Complete_tb_behav -key {Behavioral:zbrajalo_sim:Functional:Complete_tb} -tclbatch Complete_tb.tcl -log simulate.log"
xsim Complete_tb_behav -key {Behavioral:zbrajalo_sim:Functional:Complete_tb} -tclbatch Complete_tb.tcl -log simulate.log

